import streamlit as st
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick


sns.set(rc={'axes.facecolor':'#F5F6F4', 'figure.facecolor':'#F5F6F4'})

df = pd.read_csv('heart_2020_cleaned.csv')
df_yes = df[df["HeartDisease"] == "Yes"]
df_no = df[df["HeartDisease"] == "No"]

st.title("Health Tips and Variable Explanations")

tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8, tab9, tab10, tab11, tab12 = st.tabs(["Nutrition and Diet Tips", "Excersise Tips", "BMI Explanation", "Genetic Explanation", "Smoking Explanation", "Drinking Explanation", "Sex Explanation", "Age Explanation", "Diabetes Explanation", "Sleep Time Explanation", "Asthma Explanation", "Kidney Disease Explanation"])


with tab1:
    st.subheader("Nutrition and Diet Tips")
    st.caption("Diet")
    st. write("Eating a healthy diet is important for everyone, and it can be especially challenging for South Asians living in the United States to maintain their cultural traditions while also following healthy eating habits. However, it is possible to strike a balance between the two by focusing on whole, unprocessed foods, using healthier cooking methods, controlling portion sizes, and incorporating physical activity into your routine.")
    st. write("One of the keys to a healthy diet is to prioritize whole, unprocessed foods such as fruits, vegetables, whole grains, and lean proteins. These types of foods provide essential nutrients and can help you feel full and satisfied. They are also high in fiber, which can help reduce the risk of heart disease, type 2 diabetes, and certain types of cancer. When cooking traditional South Asian dishes, try to incorporate more of these types of ingredients. For example, you could add extra vegetables to your curries or serve your meals with a side of whole grains like quinoa or brown rice.")
    st. write("Traditional South Asian cooking often involves deep frying or cooking with large amounts of oil. While these methods can add flavor to your dishes, they can also be high in calories and unhealthy. Consuming too much saturated fat and trans fat can increase your risk of heart disease and other health problems. Instead, try using healthier cooking methods such as grilling, baking, or stir-frying to prepare your meals. You can also use heart-healthy oils like olive oil or avocado oil when cooking, as these are higher in monounsaturated fats and lower in saturated fats. Monounsaturated fats can help lower cholesterol levels and reduce the risk of heart disease.")
    st. write("It’s important to pay attention to portion sizes when trying to eat healthy. Even if you’re eating nutritious foods, consuming too much of them can still lead to weight gain. Being overweight or obese can increase your risk of heart disease, type 2 diabetes, and other health problems. Use smaller plates and bowls to help control portion sizes, and be mindful of how much you’re eating at each meal.")
    st. write("In addition to eating a healthy diet, it’s also important to incorporate physical activity into your routine. This can help you maintain a healthy weight and improve your overall health. Regular physical activity can help reduce the risk of heart disease, stroke, type 2 diabetes, and certain types of cancer. It can also improve mental health and reduce the risk of depression and anxiety. Find activities that you enjoy, such as walking, running, dancing, or yoga, and aim for at least 30 minutes of moderate-intensity activity each day.")
    st. write("By following these tips, you can adopt healthy eating habits while still enjoying traditional South Asian meals. It’s all about finding a balance and making small, healthy changes to your diet and lifestyle.")
    st.caption("Specific Foods")
    st. write("There are certain foods commonly consumed by South Asians that may increase their risk of heart disease and diabetes. Some examples of these foods include:")
    st. write("1. Refined grains: Many traditional South Asian dishes are made with refined grains such as white rice, white flour, and maida (a type of white flour commonly used in South Asian baking). These grains have been stripped of their outer layers, which removes much of the fiber and nutrients. Consuming too many refined grains can lead to blood sugar spikes and contribute to the development of type 2 diabetes. Examples of dishes made with refined grains include naan, paratha, poori, and bhatura.")
    st. write("2. Processed meats: Processed meats such as bacon, sausage, and salami are high in saturated fat and sodium, which can increase the risk of heart disease. These types of meats are often used in traditional South Asian dishes, such as kebabs, samosas, and biryani.")
    st. write("3. Fried foods: Deep-fried foods, such as samosas, pakoras, vadas, and bhajias, are common in South Asian cuisine. However, consuming too many fried foods can increase the risk of heart disease and obesity.")
    st. write("To maintain the integrity of traditional South Asian cuisines while still reducing the risk of heart disease and diabetes, there are a few alternative foods that you can use:")
    st. write("1. Whole grains: Instead of using refined grains, try using whole grains such as brown rice, quinoa, and whole wheat flour. These grains are higher in fiber and nutrients, and they can help regulate blood sugar levels. Examples of dishes made with whole grains include chapati, roti, dal bhat, and bajra roti.")
    st. write("2. Lean proteins: Instead of processed meats, try using lean proteins such as chicken, fish, and tofu. These types of proteins are lower in saturated fat and can help reduce the risk of heart disease. Examples of dishes made with lean proteins include chicken tikka, fish curry, tofu tikka masala, and chana masala.")
    st. write("3. Baked or grilled foods: Instead of frying your foods, try baking or grilling them instead. These methods use less oil and can help reduce the risk of heart disease and obesity. Examples of baked or grilled dishes include tandoori chicken, chicken tikka, paneer tikka, and tandoori shrimp.")
    st. write("By incorporating these alternative foods into your traditional South Asian dishes, you can still enjoy your cultural cuisine while also reducing your risk of heart disease and diabetes. It’s all about finding a balance and making small, healthy changes to your diet.")

with tab2:
    st.subheader("Exercise Tips")
    st. write("If you’re a South Asian adult with no fitness experience and you’re looking to improve your overall health, starting a regular workout routine can be a great place to begin. South Asian adults are at an increased risk for developing type 2 diabetes and heart disease, and physical activity can help reduce these risks. Here is a healthy workout routine that you can follow, even if you’re new to fitness:")
    st. write("1. Begin with low-impact activities: If you’re just starting out, it’s important to ease into your workouts slowly. Begin with low-impact activities such as walking, biking, or swimming. These activities are gentle on your joints and can help you build up your endurance and strength gradually. Aim for at least 30 minutes of moderate-intensity activity, such as brisk walking, each day.")
    st. write("2. Incorporate strength training: In addition to cardiovascular exercise, it’s important to include strength training in your routine. Strength training can help improve bone density, increase muscle mass, and boost metabolism. You don’t need to lift heavy weights to see benefits – bodyweight exercises such as push-ups, squats, and lunges can be just as effective. Aim for two to three days of strength training each week.")
    st. write("3. Vary your workouts: To keep your workouts interesting and prevent boredom, try to vary your routine. This could mean trying different types of cardio, such as running or cycling, or mixing up your strength training exercises. You could also try different workout formats, such as group fitness classes or online workouts.")
    st. write("4. Listen to your body: It’s important to listen to your body and not push yourself too hard, especially if you’re new to exercise. If you feel tired or experience any discomfort, take a break and rest. Gradually increase the intensity and duration of your workouts as you become more comfortable and fit.")
    st. write("By following this healthy workout routine, you can improve your overall health and reduce your risk of type 2 diabetes and heart disease. Remember to also focus on eating a healthy diet, getting enough sleep, and managing stress to further support your health. Consult with a healthcare professional before starting any new fitness routine, especially if you have any health conditions.")

with tab3:
    st.subheader("BMI Explanation")
    st. write("Underweight: a BMI of less than 18.5 is considered underweight. This may indicate that an individual is not getting enough nutrients or calories to support their body's needs, which can lead to health problems such as malnutrition, weakened immune system, and decreased bone density. However, it is important to note that there may be other factors, such as a medical condition or medication use, that contribute to being underweight.")
    st. write("Normal weight: a BMI of 18.5 to 24.9 is considered normal weight. This range is associated with the lowest risk of developing health problems related to excess body fat, such as diabetes, heart disease, and certain types of cancer. Maintaining a healthy weight can also improve overall physical and mental well-being.")
    st. write("Overweight: a BMI of 25 to 29.9 is considered overweight. This range is associated with an increased risk of developing health problems related to excess body fat. Individuals who are overweight may be at risk for developing conditions such as high blood pressure, high cholesterol, and type 2 diabetes. Losing weight through a combination of diet and exercise can help to reduce these risks.")
    st. write("Obese: a BMI of 30 or higher is considered obese. This range is associated with the highest risk of developing health problems related to excess body fat. Obese individuals may be at risk for developing serious conditions such as heart disease, type 2 diabetes, and certain types of cancer. Losing weight through a combination of diet, exercise, and potentially weight loss medications or surgery can help to reduce these risks and improve overall health.")
    st. write("It is important to note that BMI is not a perfect measure of body fat, as it does not take into account differences in muscle mass, bone density, and distribution of fat. Additionally, it may not be accurate for individuals who are very athletic or have a lot of muscle mass, as it does not distinguish between fat and muscle. However, it can be a useful tool for assessing an individual's risk of developing health issues related to excess body fat.")
    st. write("It is recommended that individuals aim to maintain a BMI within the normal weight range, as this is associated with a lower risk of developing health problems. However, it is also important to consider other factors, such as waist circumference and overall body composition, when determining an individual's overall health status. A healthcare professional can help to determine the most appropriate weight range for an individual based on their specific circumstances.")
    st. write("In conclusion, BMI is a simple tool used to assess body fat based on height and weight. It is important to maintain a BMI within the normal range in order to reduce the risk of developing health problems, but it is also important to consider other factors when assessing overall health status. By understanding the potential risks associated with different BMI ranges, individuals can take steps to maintain a healthy weight and improve their overall well-being.")
    
    g = sns.FacetGrid(df, col = "HeartDisease")
    g.map(sns.histplot, "BMI", stat = 'percent', color = "#C27070")
    st.pyplot(g)
    
    st.write("As shown in the graphs above, there is a lower average BMI for those without heart disease.")

with tab4: 
    st.subheader("Genetic Explanation")
    st. write("South Asians, which include people from India, Pakistan, Bangladesh, Sri Lanka, and Nepal, are known to have an increased risk of developing heart disease and type 2 diabetes. While there are several lifestyle factors that contribute to this risk, such as diet and physical activity, there is also a genetic component at play.")
    st. write("One of the main genetic factors that may increase the risk of heart disease and type 2 diabetes in South Asians is the presence of a gene called apolipoprotein (APOE). This gene plays a role in the metabolism of cholesterol and can increase the risk of heart disease when present in certain forms. Specifically, the APOE ε2 and APOE ε4 alleles have been associated with an increased risk of heart disease in South Asians. These alleles are more common in South Asian populations compared to people of European descent, which may contribute to the higher prevalence of heart disease in South Asians.")
    st. write("Another genetic factor that may contribute to the increased risk of heart disease and type 2 diabetes in South Asians is the presence of a gene called PPARG. This gene helps regulate the body’s use of fat and glucose, and variations in this gene have been linked to an increased risk of type 2 diabetes. Specifically, the PPARG Pro12Ala polymorphism has been associated with an increased risk of type 2 diabetes in South Asians.")
    st. write("In addition to genetic factors, South Asians are also more likely to develop visceral and ectopic fat, which are types of fat that accumulate around the organs and muscles, respectively. This tendency may be due to differences in body composition and fat distribution between South Asians and people of other ethnicities. Visceral and ectopic fat is more dangerous than subcutaneous fat, which is the fat that accumulates just under the skin. Visceral and ectopic fat is associated with an increased risk of heart disease and type 2 diabetes.")
    st. write("Other genetic factors that may increase the risk of heart disease and type 2 diabetes in South Asians include genes that affect insulin production and sensitivity, such as the INS VNTR polymorphism and the KCNJ11 E23K polymorphism. Additionally, genes that influence blood pressure and lipid levels, such as the AGT M235T polymorphism and the CETP TaqIB polymorphism, may also contribute to the increased risk of these conditions in South Asians.")
    st. write("It is important to note that while genetics and body composition can play a role in the increased risk of heart disease and type 2 diabetes in South Asians, lifestyle factors such as diet and physical activity also significantly impact an individual’s risk. Adopting a healthy diet and regular physical activity can help manage or reduce the risk of these conditions, regardless of genetic predisposition. It is also important to work with a healthcare professional to monitor your risk and take appropriate preventive measures.")
    st. write("In conclusion, South Asians have an increased risk of developing heart disease and type 2 diabetes due to a combination of genetic and lifestyle factors. The presence of certain genetic variations, such as the APOE and PPARG polymorphisms, and a tendency to develop visceral and ectopic fat may contribute to this increased risk. By adopting healthy habits and working with a healthcare professional, it is possible to manage or reduce the risk of these conditions and improve overall health.")

with tab5: 
    st.subheader("Smoking")
    st. write("Smoking is a major risk factor for heart disease, a leading cause of death and disability worldwide. According to the Centers for Disease Control and Prevention (CDC), smoking is responsible for about 1 in 3 deaths from heart disease in the United States. There are several ways in which smoking can contribute to the development of heart disease, including damaging the arteries, increasing blood pressure and heart rate, and increasing the risk of blood clots.")
    st. write("One of the main ways in which smoking contributes to heart disease is by damaging the arteries. The chemicals in cigarette smoke can cause the walls of the arteries to become inflamed and scarred, a process known as arteriosclerosis. This makes the arteries more rigid and less able to expand and contract properly, which can lead to reduced blood flow to the heart. This can increase the risk of angina, a type of chest pain caused by reduced blood flow to the heart, and can also lead to heart attack. In fact, the risk of heart attack is 25 times higher in smokers compared to non-smokers.")
    st. write("In addition to damaging the arteries, smoking also increases blood pressure and heart rate. The chemicals in cigarette smoke stimulate the production of adrenaline, a hormone that can cause the heart to beat faster and harder. This can put extra strain on the heart, making it more likely to develop problems over time. High blood pressure is a known risk factor for heart disease, and smoking can contribute to the development of high blood pressure. In fact, smokers are twice as likely to develop high blood pressure compared to non-smokers.")
    st. write("Finally, smoking can also increase the risk of blood clots, which can block the flow of blood to the heart and cause a heart attack. The chemicals in cigarette smoke can cause the blood to become thicker and stickier, making it more likely to form clots. Blood clots can also form in the arteries of the heart, leading to a condition called coronary artery disease, which can cause a heart attack. Smokers are twice as likely to develop blood clots compared to non-smokers.")
    st. write("In conclusion, the evidence is clear that smoking is a major risk factor for heart disease. Quitting smoking can significantly reduce the risk of developing this condition, and is one of the best things that a person can do for their heart health. If you are a smoker, it is never too late to quit and improve your heart health. The benefits of quitting smoking start almost immediately and increase over time, so don't wait to take this important step for your health.")
    
    g = sns.FacetGrid(df, col = "HeartDisease", col_wrap = 2)
    g.map(sns.histplot, "Smoking", stat = 'percent', color = "#C27070")
    st.pyplot(g)
   
    st.write("We can see that in subjects with heart disease, there is a a higher percentage of smokers and vice versa...")

with tab6:
    st.subheader("Drinking")
    st. write("Alcohol consumption can have a significant effect on heart failure, a condition in which the heart is unable to pump enough blood to meet the body's needs. Heart failure is a leading cause of death and disability worldwide, and alcohol consumption is a known risk factor for the development of this condition. There are several ways in which alcohol can contribute to the development of heart failure, including increasing blood pressure, damaging the heart muscle, and increasing the risk of arrhythmias")
    st. write("One of the main ways in which alcohol can contribute to heart failure is by increasing blood pressure. Alcohol can cause the blood vessels to constrict, which can lead to an increase in blood pressure. High blood pressure is a known risk factor for heart failure, and alcohol consumption can contribute to the development of high blood pressure. In fact, a study published in the Journal of the American College of Cardiology found that moderate to heavy alcohol consumption, defined as more than 14 drinks per week for men and more than 7 drinks per week for women, was associated with an increased risk of heart failure. The risk was found to be even higher for those who consumed more than 21 drinks per week for men and more than 14 drinks per week for women.")
    st. write("In addition to increasing blood pressure, alcohol can also damage the heart muscle. The chemicals in alcohol can cause the heart muscle to become inflamed and scarred, a process known as alcoholic cardiomyopathy. This can lead to a weaken and enlarged heart, which is less able to pump blood effectively. Alcoholic cardiomyopathy is a major cause of heart failure, and can be prevented by reducing alcohol consumption. The American Heart Association recommends that men have no more than two drinks per day and women have no more than one drink per day to reduce the risk of alcoholic cardiomyopathy and other alcohol-related health problems.")
    st. write("Finally, alcohol can also increase the risk of arrhythmias, which are abnormal heart rhythms that can lead to heart failure. Alcohol can interfere with the electrical signals that control the heart's rhythm, leading to arrhythmias. In addition, alcohol can increase the risk of blood clots, which can block the flow of blood to the heart and cause a heart attack.")
    st. write("In conclusion, alcohol consumption can have a significant effect on heart failure. Reducing alcohol consumption can help to reduce the risk of developing this condition, and is an important step in maintaining heart health. If you are concerned about your alcohol consumption and its effect on your heart health, it is important to speak with a healthcare provider for guidance. They can help you to understand the risks and benefits of alcohol consumption and provide you with advice on how to reduce your risk of heart failure and other alcohol-related health problems.")
    

with tab7: 
    st.subheader("Sex")
    st. write("Heart disease is a leading cause of death and disability worldwide, and it affects both men and women. However, there are some differences in the way that heart disease presents and progresses in men and women, and these differences can have significant impacts on the diagnosis, treatment, and outcomes of heart disease.")
    st. write("One of the main differences between men and women with heart disease is the age at which they are most likely to develop the condition. Men are more likely to develop heart disease at an earlier age than women, with the risk increasing after the age of 45. In contrast, women are more likely to develop heart disease after the age of 55. This difference in age of onset may be due to the protective effect of estrogen, a hormone that is present in higher levels in women before menopause.")
    st. write("Another difference between men and women with heart disease is the symptoms they experience. Men are more likely to experience chest pain as a symptom of heart disease, while women are more likely to experience other symptoms such as shortness of breath, nausea, and fatigue. This difference in symptoms can lead to delays in diagnosis and treatment for women, as they may not seek medical attention as quickly as men.")
    st. write("In addition to these differences, there are also some unique risk factors for heart disease in women. Pregnancy complications, such as pre-eclampsia and gestational diabetes, can increase the risk of heart disease in women. Women who have undergone menopause are also at increased risk for heart disease, as the loss of estrogen can lead to changes in the blood vessels and an increased risk of heart attack.")
    st. write("In conclusion, gender can have a significant effect on heart disease. It is important for both men and women to be aware of their risk factors and to take steps to reduce their risk, such as maintaining a healthy diet and lifestyle, quitting smoking, and getting regular medical check-ups. It is also important for healthcare providers to be aware of the unique risk factors and symptoms of heart disease in women and to provide appropriate care and treatment.")

    g = sns.FacetGrid(df, col = "Sex", hue = "AgeCategory", palette="rocket")
    g.map(sns.histplot, "HeartDisease",stat = 'percent',  multiple="dodge") 
    g.add_legend()
    st.pyplot(g)
    
with tab8:    
    st.subheader("Age")
    st. write("Heart disease is a leading cause of death and disability worldwide, and it can affect people of all ages. However, age is a major risk factor for the development of heart disease, and the risk of heart disease increases with age. This is due in part to the natural changes that occur in the body as we age, as well as the accumulation of risk factors over time")
    st. write("One of the main ways in which age can increase the risk of heart disease is by causing changes in the arteries. As we age, the arteries can become stiff and narrow, a process known as arteriosclerosis. This can reduce blood flow to the heart and increase the risk of heart attack and stroke. In addition, the risk of plaque build-up in the arteries, a condition known as atherosclerosis, also increases with age. Plaque build-up can narrow the arteries and increase the risk of heart attack and stroke.")
    st. write("Another way in which age can increase the risk of heart disease is by increasing the risk of certain conditions and diseases that are associated with heart disease. For example, the risk of high blood pressure, diabetes, and high cholesterol increases with age, and all of these conditions are known risk factors for heart disease. In addition, the risk of heart failure, a condition in which the heart is unable to pump enough blood to meet the body's needs, also increases with age.")
    st. write("In conclusion, age is a major risk factor for heart disease, and the risk of heart disease increases with age. However, there are steps that can be taken to reduce the risk of heart disease at any age, such as maintaining a healthy diet and lifestyle, quitting smoking, and getting regular medical check-ups. It is important for people of all ages to be aware of their risk factors and to take steps to reduce their risk of heart disease.")

    g = sns.FacetGrid(df.sort_values('AgeCategory', ascending=False), col = "AgeCategory", col_wrap = 4)
    g.map(sns.histplot, "HeartDisease", stat = 'percent', color = "#C27070") 
    st.pyplot(g)
    
    st.write("As the age category increases, we can see a higher prevelance of heart disease")

with tab9:
    st.subheader("Diabetes")
    st. write("People with diabetes have an increased risk of heart failure for several reasons. First, diabetes can cause changes in the arteries that increase the risk of heart disease. The high levels of sugar in the blood associated with diabetes can damage the walls of the arteries, leading to a condition called arteriosclerosis. This can make the arteries stiff and narrow, reducing blood flow to the heart and increasing the risk of heart attack and stroke.")
    st. write("In addition, diabetes is often accompanied by other risk factors for heart disease, such as high blood pressure and high cholesterol. These conditions can further increase the risk of heart disease in people with diabetes.")
    st. write("Finally, diabetes can also damage the heart muscle, leading to a condition called diabetic cardiomyopathy. This can weaken the heart and make it less able to pump blood effectively, increasing the risk of heart failure.")
    st. write("In conclusion, people with diabetes have an increased risk of heart failure due to the damage that diabetes can cause to the arteries and heart muscle, as well as the presence of other risk factors for heart disease. It is important for people with diabetes to manage their blood sugar levels and control other risk factors, such as high blood pressure and high cholesterol, to reduce the risk of heart failure and other complications.")
  
    g = sns.FacetGrid(df, col = "Diabetic", col_wrap = 4)
    g.map(sns.histplot, "HeartDisease", stat = 'percent', color = "#C27070") 
    st.pyplot(g)
    
    st.write("Of all the diabetic categories, we can see a higher percentage of heart disease in full diabetics")
    
with tab10:
    st.subheader("Sleep Time")
    st. write("There is a significant relationship between sleep time and heart disease. Studies have shown that people who get too little or too much sleep are at increased risk of developing heart disease.")
    st. write("One of the main ways in which sleep time can affect heart disease is through its effect on the hormones that regulate appetite and metabolism. Lack of sleep can lead to an increase in appetite and a decrease in the hormone leptin, which helps to regulate appetite. This can lead to weight gain, which is a known risk factor for heart disease. In addition, lack of sleep can increase the hormone ghrelin, which stimulates appetite, and decrease the hormone insulin, which helps to regulate blood sugar levels. This can increase the risk of diabetes, another risk factor for heart disease.")
    st. write("In addition to its effects on appetite and metabolism, lack of sleep can also increase the risk of heart disease by increasing blood pressure and heart rate. Studies have shown that people who get less than 7 hours of sleep per night are at increased risk of high blood pressure, which is a major risk factor for heart disease. Lack of sleep can also increase the production of stress hormones, which can increase heart rate and put extra strain on the heart.")
    st. write("On the other hand, too much sleep can also increase the risk of heart disease. Studies have shown that people who get more than 9 hours of sleep per night are at increased risk of heart disease. It is not clear exactly why this is the case, but it may be due to underlying health conditions that can both cause excessive sleep and increase the risk of heart disease.")
    st. write("In conclusion, there is a significant relationship between sleep time and heart disease. Getting the right amount of sleep, typically 7-9 hours per night for adults, is important for maintaining heart health. If you are concerned about your sleep time and its effect on your heart health, it is important to speak with a healthcare provider for guidance.")

    g = sns.FacetGrid(df, col = "HeartDisease")
    g.map(sns.boxenplot, "SleepTime", color = "#C27070") 
    st.pyplot(g)
    
    st.write("As seen in the plot above, subjects without heart disease seem to stick close to 7 hours of sleep a night.")
    st.write("While subjects with heart disease have a similar average, they are a lot more spread out with many subjects a lot below the average")
    
with tab11:
    st.subheader("Asthma")
    st. write("Asthma and heart disease are two separate conditions, but they can be interconnected in several ways. People with asthma are at increased risk of developing heart disease, and people with heart disease are also at increased risk of developing asthma.")
    st. write("One of the main ways in which asthma can increase the risk of heart disease is through its effect on blood pressure. Asthma can cause the blood vessels to constrict, which can lead to an increase in blood pressure. High blood pressure is a major risk factor for heart disease, and the risk of heart disease increases as blood pressure increases. In addition, asthma can also cause an increase in heart rate, which can put extra strain on the heart and increase the risk of heart disease.")
    st. write("People with heart disease are also at increased risk of developing asthma. This is because the same factors that increase the risk of heart disease, such as high blood pressure and high cholesterol, can also increase the risk of asthma. In addition, heart disease can cause changes in the blood vessels that can increase the risk of asthma. For example, heart failure, a condition in which the heart is unable to pump enough blood to meet the body's needs, can cause fluid to build up in the lungs, increasing the risk of asthma.")
    st. write("In conclusion, there is a relationship between asthma and heart disease, with people with asthma at increased risk of developing heart disease, and people with heart disease at increased risk of developing asthma. It is important for people with asthma or heart disease to be aware of their risk of developing the other condition and to take steps to manage their health, such as following their treatment plan and adopting a healthy lifestyle.")

    g = sns.FacetGrid(df, col = "HeartDisease")
    g.map(sns.histplot, "Asthma", stat = 'percent', color = "#C27070") 
    st.pyplot(g)
    
    st.write("We can see a higher percentage of asthma patients in those with heart disease.")

with tab12:
    st.subheader("Kidney Disease")
    st. write("There is a strong and complex relationship between kidney disease and heart disease. Kidney disease, also known as chronic kidney disease, is a condition in which the kidneys are damaged and are unable to function properly. Heart disease is a leading cause of death and disability worldwide, and it can affect people of all ages. The relationship between these two conditions is multifaceted, and there are several ways in which kidney disease can increase the risk of heart disease, as well as vice versa.")
    st. write("One of the main ways in which kidney disease can increase the risk of heart disease is through its effect on blood pressure. The kidneys play a crucial role in regulating blood pressure by releasing a hormone called renin. When the kidneys are damaged, they may not produce enough renin, which can lead to an increase in blood pressure. High blood pressure is a major risk factor for heart disease, and the risk of heart disease increases as blood pressure increases. In fact, high blood pressure is one of the leading causes of kidney disease, and it is estimated that more than half of people with chronic kidney disease also have high blood pressure.")
    st. write("In addition to its effect on blood pressure, kidney disease can also increase the risk of heart disease through its effect on the levels of certain substances in the blood. For example, kidney disease can lead to an accumulation of waste products in the blood, such as urea and creatinine, which can increase the risk of heart disease. These waste products can build up in the blood when the kidneys are not functioning properly, and they can cause inflammation and damage to the blood vessels, increasing the risk of heart disease. Kidney disease can also cause an imbalance in the levels of electrolytes in the blood, such as potassium and sodium, which can also increase the risk of heart disease.")
    st. write("Finally, kidney disease can also increase the risk of heart disease by increasing the risk of other conditions that are associated with heart disease, such as diabetes and high cholesterol. These conditions can further increase the risk of heart disease in people with kidney disease. In addition, people with heart disease are also at increased risk of developing kidney disease. This is because the same factors that increase the risk of heart disease, such as high blood pressure and high cholesterol, can also increase the risk of kidney disease. In addition, heart disease can cause changes in the blood vessels that can increase the risk of kidney disease. For example, heart failure, a condition in which the heart is unable to pump enough blood to meet the body's needs, can cause fluid to build up in the lungs, increasing the risk of kidney disease.")
    st. write("In conclusion, there is a strong and complex relationship between kidney disease and heart disease. People with kidney disease are at increased risk of developing heart disease, and people with heart disease are also at increased risk of developing kidney disease. It is important for people with kidney disease or heart disease to be aware of their risk of developing the other condition and to take steps to manage their health, such as following their treatment plan and adopting a healthy lifestyle. This can help to reduce the risk of developing these conditions and to improve overall health and well-being.")
    
    g = sns.FacetGrid(df, col = "HeartDisease")
    g.map(sns.histplot, "KidneyDisease", stat = 'percent', color = "#C27070") 
    st.pyplot(g)
    
    st.write("We can see a higher percentage of kidney disease patients in those with heart disease.")