import streamlit as st

st.title("Helpful Links")
st.header("Nutrition")
st.caption("The following links include information regarding general aspects of nutrition. The listed resources will help you create a healthier diet for yourself.")
st.markdown("- [Glycemic Index of International Dishes](https://static1.squarespace.com/static/56bce7313c44d80c62471a28/t/62dea31a60f4613038559330/1658757915429/2021_Jan_A+glycaemic+index+compendium+of+non-western+foods.pdf)")
st.markdown("- [Carbohydrate Counting Tool for South Asian Dishes](https://static1.squarespace.com/static/56bce7313c44d80c62471a28/t/56d52ab627d4bd7c5c00b9ba/1456810690847/carbcountingtool2014.pdf)")
st.markdown("- [Vegetarian Keto Dishes](https://headbangerskitchen.com/tag/vegetarian-keto-recipes/)")
st.header("Physical Activity")
st.caption("The following links will introduce you to and help ypu learn various ways of keeping yourself fit and your body healthy")
st.markdown("- [Fitness Advice for Older People](https://www.silversneakers.com/blog/simplest-way-stay-motivated-exercise/)")
st.markdown("- [Fitness Advice for Different Condition](https://www.nutrition.gov/topics/exercise-and-fitness)")
st.markdown("- [Fitness Videos in Punjabi](https://www.youtube.com/channel/UCrAaXz1hMpNJ8h9Gkn9KlCg/videos)")
st.title("Works Cited")
st.write("- Ambrose JA, Barua RS. The pathophysiology of cigarette smoking and cardiovascular disease:an update. J Am Coll Cardiol. 2004;43(10):1731-1737.doi:10.1016/j.jacc.2003.12.047.Accessed December 30, 2022.")
st.write("- Bui AL, Horwich TB, Fonarow GC. Epidemiology and risk profile of heart failure. Nat Rev Cardiol. 2011;8(1):30-41. doi:10.1038/nrcardio.2010.165.Accessed December 30, 2022.")
st.write("- Felitti VJ, Anda RF, Nordenberg D, et al. Relationship of childhood abuse and household dysfunction to many of the leading causes of death in adults. The Adverse Childhood Experiences (ACE) Study. Am J Prev Med. 1998;14(4):245-258. doi:10.1016/s0749-3797(98)00017-8.Accessed December 30, 2022. ")
st.write("- Home. Sutter Health. https://www.sutterhealth.org/health/south-asian/nutrition-healthy-weight/nutrition. Accessed December 30, 2022. ")
st.write("- LaPorte RE, Cresanta JL, Kuller LH. The relationship of alcohol consumption to atherosclerotic heart disease. Prev Med. 1980;9(1):22-40. doi:10.1016/0091-7435(80)90057-2.Accessed December 30, 2022.  ")
st.write("- O'connor A. Why do South Asians have such high rates of heart disease? The New York Times. https://www.nytimes.com/2019/02/12/well/live/why-do-south-asians-have-such-high-rates-of-heart-disease.html#:~:text=People%20of%20South%20Asian%20descent,up%20to%20a%20decade%20earlier. Published February 12, 2019. Accessed December 30, 2022. ")
st.write("- Palaniappan L, Garg A, Enas E, et al. South Asian Cardiovascular Disease & Cancer Risk: Genetics & Pathophysiology. J Community Health. 2018;43(6):1100-1114. doi:10.1007/s10900-018-0527-8.Accessed December 30, 2022.  ")
st.write("- Pytlak, K.(2022). Personal Key Indicators of Heart Disease. https://www.kaggle.com/datasets/kamilpytlak/personal-key-indicators-of-heart-disease?select=heart_2020_cleaned.csv.Accessed December 30, 2022. ")
st.write("- Singh A. Asians have a particularly high susceptibility to type 2 diabetes and a healthy diet is one of the main ways in which diabetes can be controlled. Diabetes. https://www.diabetes.co.uk/south-asian/healthy-eating-tips-for-south-asians.html. Published November 7, 2022. Accessed December 30, 2022. ")
st.write("- Understanding your healthy weight: BMI and WHR. Understanding your healthy weight: BMI and WHR - Food and nutrition | NHS inform. https://www.nhsinform.scot/healthy-living/food-and-nutrition/healthy-eating-and-weight-loss/understanding-your-health-and-weight-body-mass-index-bmi#:~:text=BMI%20ranges&amp;text=under%2018.5%20%E2%80%93%20This%20is%20described,This%20is%20described%20as%20obesity. Accessed December 30, 2022. ")